import type { Metadata } from 'next'
import { IBM_Plex_Mono as FontMono, Inter as FontSans } from 'next/font/google'
import './globals.css'
import 'yet-another-react-lightbox/styles.css'

const fontMono = FontMono({
  weight: ['400', '700'],
  display: 'swap',
  subsets: ['latin'],
})

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  // metadataBase: new URL(process.env.NEXT_PUBLIC_URL as string),
  title: 'Obsidian Blog',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${fontMono.className} ${fontSans.className} font-sans antialiased overflow-y-scroll`}
      >
        <main className="">{children}</main>
      </body>
    </html>
  )
}
