import type { Metadata } from 'next'
import { IBM_Plex_Mono } from 'next/font/google'
import './globals.css'
import 'yet-another-react-lightbox/styles.css'

const PlexMono = IBM_Plex_Mono({
  weight: ['400', '700'],
  display: 'swap',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${PlexMono.className} overflow-y-scroll`}>
        <main className="p-5 mx-auto w-full max-w-screen-lg">{children}</main>
      </body>
    </html>
  )
}
